// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class AccessorialWorkflowTask
{
    public int Id { get; set; }

    public int AccessorialChargeId { get; set; }

    public int EventTypeId { get; set; }

    public int StageId { get; set; }

    public int Sequence { get; set; }

    public bool Required { get; set; }

    public string ConfigJson { get; set; }

    public bool Active { get; set; }

    public virtual TucEventType EventType { get; set; }
}