// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class ActionExecutionDetail
{
    public long Id { get; set; }

    public int ExecutionLogId { get; set; }

    public string ActionType { get; set; }

    public bool Success { get; set; }

    public string Detail { get; set; }

    public string ErrorMessage { get; set; }

    public int DurationMs { get; set; }

    public virtual AutomationExecutionLog ExecutionLog { get; set; }
}