// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class AgentCoverageArea
{
    public int Id { get; set; }

    public int AgentId { get; set; }

    public string AreaName { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public virtual TucAgent Agent { get; set; }
}