// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class AgentOnboarding
{
    public int Id { get; set; }

    public int? ProspectAgentId { get; set; }

    public int? QuotesQuoteId { get; set; }

    public int? AgentId { get; set; }

    public int? ClientId { get; set; }

    public string CompanyName { get; set; }

    public string ContactName { get; set; }

    public string ContactEmail { get; set; }

    public string ContactPhone { get; set; }

    public string OnboardingType { get; set; }

    public string AssociationSource { get; set; }

    public string Status { get; set; }

    public byte CurrentStep { get; set; }

    public byte TotalSteps { get; set; }

    public bool DocumentsSubmitted { get; set; }

    public bool DocumentsVerified { get; set; }

    public int? VerifiedByUserId { get; set; }

    public DateTime? VerifiedDate { get; set; }

    public int? AssignedToUserId { get; set; }

    public string Notes { get; set; }

    public int InitiatedByUserId { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime UpdatedDate { get; set; }

    public DateTime? CompletedDate { get; set; }

    public virtual ProspectAgent ProspectAgent { get; set; }

    public virtual QuotesQuote QuotesQuote { get; set; }
}