// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class AgentCourierRate
{
    public int Id { get; set; }

    public int AgentId { get; set; }

    public int CourierId { get; set; }

    public int? VehicleSizeId { get; set; }

    public decimal PayPercentage { get; set; }

    public decimal BonusPercentage { get; set; }

    public DateOnly EffectiveFrom { get; set; }

    public DateOnly? EffectiveTo { get; set; }

    public bool IsActive { get; set; }

    public int CreatedByUserId { get; set; }

    public DateTime CreatedDate { get; set; }

    public int UpdatedByUserId { get; set; }

    public DateTime UpdatedDate { get; set; }

    public string Notes { get; set; }
}