// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class AgentCoverageAreaZipcode
{
    public int Id { get; set; }

    public int AgentCoverageAreaId { get; set; }

    public int ZipPolygonId { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public virtual AgentCoverageArea AgentCoverageArea { get; set; }

    public virtual ZipPolygon ZipPolygon { get; set; }
}