// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class AppConfig
{
    public int Id { get; set; }

    public string ConfigKey { get; set; }

    public string ConfigValue { get; set; }

    public string DataType { get; set; }

    public string Category { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastModified { get; set; }

    public string LastModifiedBy { get; set; }
}