// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class AutomationCondition
{
    public int Id { get; set; }

    public int RuleId { get; set; }

    public string ConditionType { get; set; }

    public string JobTypeFilter { get; set; }

    public int? TimeThreshold { get; set; }

    public int? TimeOffset { get; set; }

    public string ScheduleReference { get; set; }

    public string PriorityFilter { get; set; }

    public int? SortOrder { get; set; }

    public string StatusFilter { get; set; }

    public bool? HasAdvancedOptions { get; set; }

    public string SpeedFilter { get; set; }

    public string FromSiteFilter { get; set; }

    public string ToSiteFilter { get; set; }

    public string FromRegionFilter { get; set; }

    public string ToRegionFilter { get; set; }

    public string ClientFilter { get; set; }

    public string StatusConditionMode { get; set; }

    public int? StatusId { get; set; }

    public string ScheduledTimeField { get; set; }

    public int? OffsetValue { get; set; }

    public string OffsetUnit { get; set; }

    public string ScanTypes { get; set; }

    public virtual AutomationRule Rule { get; set; }
}