// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class AutomationExecutionLog
{
    public int Id { get; set; }

    public int RuleId { get; set; }

    public int? JobId { get; set; }

    public string JobNumber { get; set; }

    public DateTime ExecutedDate { get; set; }

    public bool Success { get; set; }

    public string ErrorMessage { get; set; }

    public string RuleName { get; set; }

    public bool ConditionsMet { get; set; }

    public string TriggerType { get; set; }

    public string TriggerDetail { get; set; }

    public int ActionsExecuted { get; set; }

    public string ActionsSummary { get; set; }

    public int DurationMs { get; set; }

    public virtual ICollection<ActionExecutionDetail> ActionExecutionDetails { get; set; } = new List<ActionExecutionDetail>();
}