// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class AutomationAction
{
    public int Id { get; set; }

    public int RuleId { get; set; }

    public string ActionType { get; set; }

    public int? EventTypeId { get; set; }

    public string TargetValue { get; set; }

    public string TaskTitle { get; set; }

    public string TaskDescription { get; set; }

    public int? TaskPriority { get; set; }

    public string EmailSubject { get; set; }

    public string EmailTemplate { get; set; }

    public string EventMessage { get; set; }

    public int? SortOrder { get; set; }

    public string ReplyToEmail { get; set; }

    public string Smsrecipient { get; set; }

    public string Smsmessage { get; set; }

    public bool? IsClientSpecific { get; set; }

    public int? ClientId { get; set; }

    public string ClientContactIds { get; set; }

    public string EmailRecipient { get; set; }

    public bool? IsSendEmailClientSpecific { get; set; }

    public int? SendEmailClientId { get; set; }

    public string SendEmailClientContactIds { get; set; }

    public string CustomEmailAddresses { get; set; }

    public string CustomSmsNumbers { get; set; }

    public bool? IsCustomEmailClientSpecific { get; set; }

    public int? CustomEmailClientId { get; set; }

    public bool? IsCustomSmsClientSpecific { get; set; }

    public int? CustomSmsClientId { get; set; }

    public int? CourierId { get; set; }

    public int? AgentId { get; set; }

    public int? ToStatusId { get; set; }

    public int? FromStatusId { get; set; }

    public int? TaskTemplateId { get; set; }

    public int? TaskAssigneeId { get; set; }

    public int? TaskAssigneeGroupId { get; set; }

    public int? TaskDueOffsetMinutes { get; set; }

    public int? NotificationTemplateId { get; set; }

    public string SmsRecipientType { get; set; }

    public string SmsFixedNumber { get; set; }

    public string SmsMessageContent { get; set; }

    public virtual TucEventType EventType { get; set; }

    public virtual AutomationRule Rule { get; set; }
}