// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class AutomationRule
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public bool IsDeleted { get; set; }

    public string ConditionMatchMode { get; set; }

    public bool AllCustomers { get; set; }

    public string CustomerIds { get; set; }

    public bool AllSpeeds { get; set; }

    public string SpeedIds { get; set; }

    public bool AllJobStatuses { get; set; }

    public string JobStatusIds { get; set; }

    public bool AllPriorities { get; set; }

    public string PriorityIds { get; set; }

    public bool AllFromSites { get; set; }

    public string FromSiteIds { get; set; }

    public bool AllToSites { get; set; }

    public string ToSiteIds { get; set; }

    public bool AllFromRegions { get; set; }

    public string FromRegionIds { get; set; }

    public bool AllToRegions { get; set; }

    public string ToRegionIds { get; set; }

    public int? TimeThreshold { get; set; }

    public virtual ICollection<AutomationAction> AutomationActions { get; set; } = new List<AutomationAction>();

    public virtual ICollection<AutomationCondition> AutomationConditions { get; set; } = new List<AutomationCondition>();
}