// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class ComplianceProfileRequirement
{
    public int Id { get; set; }

    public int ProfileId { get; set; }

    public int DocumentTypeId { get; set; }

    public bool Mandatory { get; set; }

    public int SortOrder { get; set; }

    public bool QuizRequired { get; set; }

    public int? QuizId { get; set; }

    public virtual DocumentType DocumentType { get; set; }

    public virtual ComplianceProfile Profile { get; set; }
}