// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class ComplianceProfile
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool IsDefault { get; set; }

    public bool IsActive { get; set; }

    public DateTime Created { get; set; }

    public DateTime? Modified { get; set; }

    public virtual ICollection<ComplianceProfileClient> ComplianceProfileClients { get; set; } = new List<ComplianceProfileClient>();

    public virtual ICollection<ComplianceProfileRequirement> ComplianceProfileRequirements { get; set; } = new List<ComplianceProfileRequirement>();
}