// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class ComplianceProfileClient
{
    public int Id { get; set; }

    public int ProfileId { get; set; }

    public string ClientName { get; set; }

    public virtual ComplianceProfile Profile { get; set; }
}