// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class CourierDocument
{
    public int Id { get; set; }

    public int? CourierId { get; set; }

    public int? ApplicantId { get; set; }

    public int DocumentTypeId { get; set; }

    public string S3key { get; set; }

    public string FileName { get; set; }

    public string ContentType { get; set; }

    public long Length { get; set; }

    public DateTime UploadedDate { get; set; }

    public string UploadedBy { get; set; }

    public string VerifyStatus { get; set; }

    public DateTime? VerifiedDate { get; set; }

    public string VerifiedBy { get; set; }

    public string RejectReason { get; set; }

    public DateOnly? ExpiryDate { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string AiSuggestedDecision { get; set; }

    public DateOnly? AiSuggestedExpiry { get; set; }

    public string AiRationale { get; set; }

    public string AiModel { get; set; }

    public DateTime? AiReviewedDate { get; set; }

    public virtual CourierApplicant Applicant { get; set; }

    public virtual TucCourier Courier { get; set; }

    public virtual DocumentType DocumentType { get; set; }
}