// <auto-generated> Hand-authored for courier modal §11 compliance-profile assignment (2026-06-22); reconcile on next EF Power Tools regen. </auto-generated>
#nullable disable
using System;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

// Many-to-many: a ComplianceProfile assigned to a courier (courier modal §11).
// The courier's required-document list is the union of the assigned profiles'
// ComplianceProfileRequirements. Mirrors the agent-side TucAgentComplianceProfile.
// Mapped in DynamicDespatchDbContext (excluded from EFPT scaffold so the
// configuration survives regen).
public partial class CourierComplianceProfile
{
    public int UccpId { get; set; }
    public int CourierId { get; set; }     // -> tucCourier.uccrID
    public int ProfileId { get; set; }     // -> ComplianceProfiles.Id
    public DateTime AssignedDate { get; set; }
    public string AssignedBy { get; set; }
}
