// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class DespatchContext : DbContext
{
    public DespatchContext(DbContextOptions<DespatchContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AccessorialWorkflowTask> AccessorialWorkflowTasks { get; set; }

    public virtual DbSet<AppConfig> AppConfigs { get; set; }

    public virtual DbSet<JobBarcode> JobBarcodes { get; set; }

    public virtual DbSet<JobPhoto> JobPhotos { get; set; }

    public virtual DbSet<JobWorkflowStep> JobWorkflowSteps { get; set; }

    public virtual DbSet<TucClient> TucClients { get; set; }

    public virtual DbSet<TucEventTemplate> TucEventTemplates { get; set; }

    public virtual DbSet<TucEventTemplateDetail> TucEventTemplateDetails { get; set; }

    public virtual DbSet<TucEventType> TucEventTypes { get; set; }

    public virtual DbSet<TucEventTypeEventTypeGroup> TucEventTypeEventTypeGroups { get; set; }

    public virtual DbSet<TucEventTypeGroup> TucEventTypeGroups { get; set; }

    public virtual DbSet<TucJobStatus> TucJobStatuses { get; set; }

    public virtual DbSet<TucJobType> TucJobTypes { get; set; }

    public virtual DbSet<TblUser> TblUsers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Latin1_General_CI_AS");

        modelBuilder.Entity<AccessorialWorkflowTask>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Accessor__3214EC07B221C1B5");

            entity.ToTable("AccessorialWorkflowTask");

            entity.HasIndex(e => e.AccessorialChargeId, "IX_AWT_Accessorial").HasFilter("([Active]=(1))");

            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.Required).HasDefaultValue(true);

            entity.HasOne(d => d.EventType).WithMany(p => p.AccessorialWorkflowTasks)
                .HasForeignKey(d => d.EventTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AWT_EventType");
        });

        modelBuilder.Entity<AppConfig>(entity =>
        {
            entity.ToTable("AppConfig");

            entity.HasIndex(e => e.ConfigKey, "UQ_AppConfig_ConfigKey").IsUnique();

            entity.Property(e => e.Category)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("feature");
            entity.Property(e => e.ConfigKey)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Created).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.DataType)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("string");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.LastModifiedBy).HasMaxLength(50);
        });

        modelBuilder.Entity<JobBarcode>(entity =>
        {
            entity.ToTable("JobBarcode");

            entity.HasIndex(e => e.JobId, "IX_JobBarcode_JobId");

            entity.Property(e => e.BarcodeType).HasMaxLength(50);
            entity.Property(e => e.BarcodeValue)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.GpsLatitude).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.GpsLongitude).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.ScannedAt).HasDefaultValueSql("(getutcdate())");
        });

        modelBuilder.Entity<JobPhoto>(entity =>
        {
            entity.ToTable("JobPhoto");

            entity.HasIndex(e => e.JobId, "IX_JobPhoto_JobId");

            entity.Property(e => e.BlobUrl)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.CapturedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.GpsLatitude).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.GpsLongitude).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.Notes).HasMaxLength(500);
            entity.Property(e => e.PhotoType)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("delivery");
            entity.Property(e => e.ThumbnailUrl).HasMaxLength(500);
        });

        modelBuilder.Entity<JobWorkflowStep>(entity =>
        {
            entity.ToTable("JobWorkflowStep");

            entity.HasIndex(e => e.JobId, "IX_JobWorkflowStep_JobId");

            entity.Property(e => e.BlobUrl).HasMaxLength(500);
            entity.Property(e => e.DataType).HasMaxLength(20);
            entity.Property(e => e.GpsLatitude).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.GpsLongitude).HasColumnType("decimal(9, 6)");

            entity.HasOne(d => d.TemplateDetail).WithMany(p => p.JobWorkflowSteps)
                .HasForeignKey(d => d.TemplateDetailId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_JobWorkflowStep_TemplateDetail");
        });

        modelBuilder.Entity<TucClient>(entity =>
        {
            entity.HasKey(e => e.UcclId)
                .IsClustered(false)
                .HasAnnotation("SqlServer:FillFactor", 80);

            entity.ToTable("tucClient", tb =>
                {
                    tb.HasTrigger("UTL_trgClient_Update");
                    tb.HasTrigger("tucClient_Insert");
                });

            entity.HasIndex(e => e.UcclCode, "IDX_tucClient_ucclCode")
                .IsUnique()
                .HasFillFactor(80);

            entity.HasIndex(e => e.InvoiceScheduleId, "IX_InvoiceScheduleId");

            entity.HasIndex(e => e.InvoiceTemplateId, "IX_InvoiceTemplateId");

            entity.HasIndex(e => e.PaymentTermId, "IX_PaymentTermId");

            entity.HasIndex(e => e.XeroId, "IX_XeroId");

            entity.HasIndex(e => e.UcclName, "Name").IsUnique();

            entity.HasIndex(e => e.SiteId, "SiteID");

            entity.HasIndex(e => e.UtaddtionalItemRateCodeId, "UTAddtionalItemRateCodeID");

            entity.HasIndex(e => e.UtrateCodeId, "UTRateCodeID");

            entity.HasIndex(e => e.UcclBillingType, "ucclBillingType");

            entity.HasIndex(e => e.UcclIndustry, "ucclIndustry");

            entity.HasIndex(e => e.UcclSuburbId, "ucclSuburbID").HasFillFactor(80);

            entity.Property(e => e.UcclId).HasColumnName("ucclID");
            entity.Property(e => e.AccountProfileId).HasColumnName("AccountProfileID");
            entity.Property(e => e.AccountsContact).HasMaxLength(100);
            entity.Property(e => e.AccountsEmail).HasMaxLength(500);
            entity.Property(e => e.AccountsPhone).HasMaxLength(100);
            entity.Property(e => e.AddonPercentage).HasColumnType("numeric(5, 4)");
            entity.Property(e => e.AddressExtras).HasMaxLength(200);
            entity.Property(e => e.AddressLine1).HasMaxLength(255);
            entity.Property(e => e.AddressLine2).HasMaxLength(255);
            entity.Property(e => e.AddressLine3).HasMaxLength(255);
            entity.Property(e => e.AddressLine4).HasMaxLength(255);
            entity.Property(e => e.AddressLine5).HasMaxLength(255);
            entity.Property(e => e.AddressLine6).HasMaxLength(255);
            entity.Property(e => e.AddressLine7).HasMaxLength(255);
            entity.Property(e => e.AddressLine8).HasMaxLength(255);
            entity.Property(e => e.AddressStreetName).HasMaxLength(200);
            entity.Property(e => e.AirNzknownShipper)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_AirNZKnownShipper")
                .HasColumnName("AirNZKnownShipper");
            entity.Property(e => e.AirNzmargin)
                .HasDefaultValue(0.57m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_AirNZMargin")
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("AirNZMargin");
            entity.Property(e => e.AlertLateDelivery).HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_AlertLateDelivery");
            entity.Property(e => e.AlertLatePickUp).HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_AlertLatePickUp");
            entity.Property(e => e.ApplyCitySurcharge)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_ApplyCitySurcharge");
            entity.Property(e => e.BaggageActive).HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_BaggageActive");
            entity.Property(e => e.BaggageRateCodeId).HasColumnName("BaggageRateCodeID");
            entity.Property(e => e.BulkAternoonHomePickupTime).HasColumnType("datetime");
            entity.Property(e => e.BulkHomeDeliveryPickupRateId).HasColumnName("BulkHomeDeliveryPickupRateID");
            entity.Property(e => e.BulkHomeDeliveryVanItemSurcharge).HasColumnType("money");
            entity.Property(e => e.ChilledTruckExcessZoneRateCodeId).HasColumnName("ChilledTruckExcessZoneRateCodeID");
            entity.Property(e => e.ChilledTruckHireRateCodeId).HasColumnName("ChilledTruckHireRateCodeID");
            entity.Property(e => e.ChilledTruckRateCodeId).HasColumnName("ChilledTruckRateCodeID");
            entity.Property(e => e.ChilledVanHireRateCodeId).HasColumnName("ChilledVanHireRateCodeID");
            entity.Property(e => e.CitySurchargeRate)
                .HasDefaultValue(1.75m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_CitySurchargeRate")
                .HasColumnType("money");
            entity.Property(e => e.CommissionDate).HasColumnType("datetime");
            entity.Property(e => e.CourierPercentage).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.CreateBulkHomeDeliveryPickup)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__tucClient__Creat__163A3110");
            entity.Property(e => e.Created).HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.DangerousServiceRateCodeId).HasColumnName("DangerousServiceRateCodeID");
            entity.Property(e => e.DeliverDifferent)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__tucClient__Deliv__1AFEE62D");
            entity.Property(e => e.DgdryIce)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("DGDryIce");
            entity.Property(e => e.Dgfee)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("DGFee");
            entity.Property(e => e.Discount)
                .HasAnnotation("Relational:DefaultConstraintName", "default_Discount")
                .HasColumnType("decimal(5, 4)");
            entity.Property(e => e.DisplayRateRef).HasAnnotation("Relational:DefaultConstraintName", "DF__tucClient__Displ__0DA4EB0F");
            entity.Property(e => e.DropoffReport).HasMaxLength(10);
            entity.Property(e => e.EconomyActive).HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_EconomyActive");
            entity.Property(e => e.EconomyFlightMarkup).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.EconomyFlightOffPeak1RateId).HasColumnName("EconomyFlightOffPeak1RateID");
            entity.Property(e => e.EconomyFlightOffPeak2RateId).HasColumnName("EconomyFlightOffPeak2RateID");
            entity.Property(e => e.EconomyFlightOffPeak3RateId).HasColumnName("EconomyFlightOffPeak3RateID");
            entity.Property(e => e.EconomyFlightOffPeak4RateId).HasColumnName("EconomyFlightOffPeak4RateID");
            entity.Property(e => e.EconomyFlightOffPeakKg1rateId).HasColumnName("EconomyFlightOffPeakKG1RateID");
            entity.Property(e => e.EconomyFlightOffPeakKg2rateId).HasColumnName("EconomyFlightOffPeakKG2RateID");
            entity.Property(e => e.EconomyFlightOffPeakKg3rateId).HasColumnName("EconomyFlightOffPeakKG3RateID");
            entity.Property(e => e.EconomyFlightOffPeakKg4rateId).HasColumnName("EconomyFlightOffPeakKG4RateID");
            entity.Property(e => e.EconomyFlightPeak1RateId).HasColumnName("EconomyFlightPeak1RateID");
            entity.Property(e => e.EconomyFlightPeak2RateId).HasColumnName("EconomyFlightPeak2RateID");
            entity.Property(e => e.EconomyFlightPeak3RateId).HasColumnName("EconomyFlightPeak3RateID");
            entity.Property(e => e.EconomyFlightPeak4RateId).HasColumnName("EconomyFlightPeak4RateID");
            entity.Property(e => e.EconomyFlightPeakKg1rateId).HasColumnName("EconomyFlightPeakKG1RateID");
            entity.Property(e => e.EconomyFlightPeakKg2rateId).HasColumnName("EconomyFlightPeakKG2RateID");
            entity.Property(e => e.EconomyFlightPeakKg3rateId).HasColumnName("EconomyFlightPeakKG3RateID");
            entity.Property(e => e.EconomyFlightPeakKg4rateId).HasColumnName("EconomyFlightPeakKG4RateID");
            entity.Property(e => e.EconomyMinimumJobRateCodeId).HasColumnName("EconomyMinimumJobRateCodeID");
            entity.Property(e => e.EconomyRateCodeId).HasColumnName("EconomyRateCodeID");
            entity.Property(e => e.EconomyRun1).HasColumnType("datetime");
            entity.Property(e => e.EconomyRun2).HasColumnType("datetime");
            entity.Property(e => e.EconomyRun3).HasColumnType("datetime");
            entity.Property(e => e.EconomyRun4).HasColumnType("datetime");
            entity.Property(e => e.EconomyRun5).HasColumnType("datetime");
            entity.Property(e => e.EconomyRun6).HasColumnType("datetime");
            entity.Property(e => e.EconomyRun7).HasColumnType("datetime");
            entity.Property(e => e.EconomyRun8).HasColumnType("datetime");
            entity.Property(e => e.EconomyRunItemsExcessRateCodeId).HasColumnName("EconomyRunItemsExcessRateCodeID");
            entity.Property(e => e.EconomyRunRateCodeId).HasColumnName("EconomyRunRateCodeID");
            entity.Property(e => e.EconomyRuns).HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_EconomyRuns");
            entity.Property(e => e.EconomyZones).HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_EconomyZones");
            entity.Property(e => e.ExpressRateCodeId).HasColumnName("ExpressRateCodeID");
            entity.Property(e => e.FastPalletExpressRateCodeId).HasColumnName("FastPalletExpressRateCodeID");
            entity.Property(e => e.FastPalletStandardRateCodeId).HasColumnName("FastPalletStandardRateCodeID");
            entity.Property(e => e.FastPalletSuperRateCodeId).HasColumnName("FastPalletSuperRateCodeID");
            entity.Property(e => e.FastParcelRateCodeId).HasColumnName("FastParcelRateCodeID");
            entity.Property(e => e.FrozenTruckExcessZoneRateCodeId).HasColumnName("FrozenTruckExcessZoneRateCodeID");
            entity.Property(e => e.FrozenTruckHireRateCodeId).HasColumnName("FrozenTruckHireRateCodeID");
            entity.Property(e => e.FrozenTruckRateCodeId).HasColumnName("FrozenTruckRateCodeID");
            entity.Property(e => e.GssregularPickupClient)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__tucClient__GSSRe__108157BA")
                .HasColumnName("GSSRegularPickupClient");
            entity.Property(e => e.GssregularPickupTime)
                .HasColumnType("datetime")
                .HasColumnName("GSSRegularPickupTime");
            entity.Property(e => e.HamiltonDayRunDeliveryRateCodeId).HasColumnName("HamiltonDayRunDeliveryRateCodeID");
            entity.Property(e => e.HamiltonDayRunPurateCodeId).HasColumnName("HamiltonDayRunPURateCodeID");
            entity.Property(e => e.HamiltonNextDayDeliveryRateCodeId).HasColumnName("HamiltonNextDayDeliveryRateCodeID");
            entity.Property(e => e.HamiltonNextDayPurateCodeId).HasColumnName("HamiltonNextDayPURateCodeID");
            entity.Property(e => e.HamiltonRunAdditionalItemsRateCodeId).HasColumnName("HamiltonRunAdditionalItemsRateCodeID");
            entity.Property(e => e.HiabHourRateCodeId).HasColumnName("HiabHourRateCodeID");
            entity.Property(e => e.IfPickupClientRateUsingZones).HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_IfPickupClientRateUsingZones");
            entity.Property(e => e.InternetDisplaySavedJobsAsCombo)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_InternetDisplaySavedJobsAsCombo");
            entity.Property(e => e.InternetRebate)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_InternetRebate")
                .HasColumnType("money");
            entity.Property(e => e.InternetShowPickUpLocation)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_InternetShowPickUpLocation");
            entity.Property(e => e.Invoice)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_Invoice");
            entity.Property(e => e.InvoiceEmail).HasMaxLength(500);
            entity.Property(e => e.InvoiceGroupBy).HasMaxLength(50);
            entity.Property(e => e.InvoiceMemo).HasMaxLength(100);
            entity.Property(e => e.InvoiceMethod).HasMaxLength(50);
            entity.Property(e => e.IsFeaturedClient).HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_IsFeaturedClient");
            entity.Property(e => e.JobPrefix).HasMaxLength(3);
            entity.Property(e => e.LastModified).HasColumnType("datetime");
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Latitude).HasColumnType("decimal(18, 9)");
            entity.Property(e => e.Longitude).HasColumnType("decimal(18, 9)");
            entity.Property(e => e.MarkUp).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.MedicalActive)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_MedicalActive");
            entity.Property(e => e.MedicalRunAdditionalItemsRateId).HasColumnName("MedicalRunAdditionalItemsRateID");
            entity.Property(e => e.MedicalRunFirstItemRateId).HasColumnName("MedicalRunFirstItemRateID");
            entity.Property(e => e.NextFlight1KgrateId).HasColumnName("NextFlight1KGRateID");
            entity.Property(e => e.NextFlight1RateId).HasColumnName("NextFlight1RateID");
            entity.Property(e => e.NextFlight2KgrateId).HasColumnName("NextFlight2KGRateID");
            entity.Property(e => e.NextFlight2RateId).HasColumnName("NextFlight2RateID");
            entity.Property(e => e.NextFlight3KgrateId).HasColumnName("NextFlight3KGRateID");
            entity.Property(e => e.NextFlight3RateId).HasColumnName("NextFlight3RateID");
            entity.Property(e => e.NextFlight4KgrateId).HasColumnName("NextFlight4KGRateID");
            entity.Property(e => e.NextFlight4RateId).HasColumnName("NextFlight4RateID");
            entity.Property(e => e.NextFlightMarkup).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.NoUtpickUp)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__tucClient__NoUTP__15460CD7")
                .HasColumnName("NoUTPickUp");
            entity.Property(e => e.NzPostSiteCode)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.OvernightPickupNotRequired)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_OvernightPickupNotRequired");
            entity.Property(e => e.OversizeRateCodeId).HasColumnName("OversizeRateCodeID");
            entity.Property(e => e.PpdgraceDays)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_PPDGraceDays")
                .HasColumnName("PPDGraceDays");
            entity.Property(e => e.Ppdrate)
                .HasDefaultValue(0.05m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_PPDRate")
                .HasColumnType("decimal(18, 4)")
                .HasColumnName("PPDRate");
            entity.Property(e => e.PrivateAddressSurchargeRateCodeId).HasColumnName("PrivateAddressSurchargeRateCodeID");
            entity.Property(e => e.PromoCode).HasMaxLength(50);
            entity.Property(e => e.PromptForEmailAddress)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_PromptForEmailAddress");
            entity.Property(e => e.PurchaseOrderNumber).HasMaxLength(100);
            entity.Property(e => e.RateRr).HasColumnName("RateRR");
            entity.Property(e => e.RateShortRr)
                .HasDefaultValue(52)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_RateShortRR")
                .HasColumnName("RateShortRR");
            entity.Property(e => e.ReferenceAdefineList)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_ReferenceADefineList")
                .HasColumnName("ReferenceADefineList");
            entity.Property(e => e.ReferenceAmandatory)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_ReferenceAMandatory")
                .HasColumnName("ReferenceAMandatory");
            entity.Property(e => e.ReferenceAmessage)
                .HasMaxLength(500)
                .HasColumnName("ReferenceAMessage");
            entity.Property(e => e.ReferenceBdefineList)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_ReferenceBDefineList")
                .HasColumnName("ReferenceBDefineList");
            entity.Property(e => e.ReferenceBmandatory)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_ReferenceBMandatory")
                .HasColumnName("ReferenceBMandatory");
            entity.Property(e => e.ReferenceBmessage)
                .HasMaxLength(500)
                .HasColumnName("ReferenceBMessage");
            entity.Property(e => e.ReferenceCdefineList)
                .HasAnnotation("Relational:DefaultConstraintName", "ReferenceCDefineList")
                .HasColumnName("ReferenceCDefineList");
            entity.Property(e => e.ReferenceCmandatory)
                .HasAnnotation("Relational:DefaultConstraintName", "ReferenceCMandatory")
                .HasColumnName("ReferenceCMandatory");
            entity.Property(e => e.ReferenceCmessage)
                .HasMaxLength(500)
                .HasColumnName("ReferenceCMessage");
            entity.Property(e => e.RemoteJobs).HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_RemoteJobs");
            entity.Property(e => e.RerateJobs)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "RerateJobs");
            entity.Property(e => e.RuralDeliveryRateCodeId).HasColumnName("RuralDeliveryRateCodeID");
            entity.Property(e => e.Sddenabled)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__tucClient__SDDEn__6EEF5278")
                .HasColumnName("SDDEnabled");
            entity.Property(e => e.Sdrenabled)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__tucClient__SDREn__6FE376B1")
                .HasColumnName("SDREnabled");
            entity.Property(e => e.ShowMap).HasAnnotation("Relational:DefaultConstraintName", "DF__tucClient__ShowM__0AC87E64");
            entity.Property(e => e.ShowNwagent)
                .HasDefaultValue(true)
                .HasColumnName("ShowNWAgent");
            entity.Property(e => e.ShowNwflight)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__tucClient__ShowN__1A0AC1F4")
                .HasColumnName("ShowNWFlight");
            entity.Property(e => e.SigRequiredDefault).HasMaxLength(500);
            entity.Property(e => e.SiteId).HasColumnName("SiteID");
            entity.Property(e => e.SiteUrl)
                .HasMaxLength(500)
                .HasColumnName("SiteURL");
            entity.Property(e => e.Smsname)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("SMSName");
            entity.Property(e => e.StartingWeightExcess)
                .HasDefaultValue(30)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_StartingWeightExcess");
            entity.Property(e => e.StripeClient).HasAnnotation("Relational:DefaultConstraintName", "DF__tucClient__Strip__172E5549");
            entity.Property(e => e.StripeClientId)
                .HasMaxLength(50)
                .HasColumnName("StripeClientID");
            entity.Property(e => e.TailLiftRateCodeId).HasColumnName("TailLiftRateCodeID");
            entity.Property(e => e.TrackingEta).HasColumnName("TrackingETA");
            entity.Property(e => e.TruckBulkRateCodeId).HasColumnName("TruckBulkRateCodeID");
            entity.Property(e => e.TruckCitySurchargeRate)
                .HasDefaultValue(10m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_TruckCitySurchargeRate")
                .HasColumnType("money");
            entity.Property(e => e.TruckEconomyExcessZoneRateCodeId).HasColumnName("TruckEconomyExcessZoneRateCodeID");
            entity.Property(e => e.TruckEconomyRateCodeId).HasColumnName("TruckEconomyRateCodeID");
            entity.Property(e => e.TruckExcessPalletEconomyRateCodeId).HasColumnName("TruckExcessPalletEconomyRateCodeID");
            entity.Property(e => e.TruckExcessPalletFastRateCodeId).HasColumnName("TruckExcessPalletFastRateCodeID");
            entity.Property(e => e.TruckExcessPalletSlowRateCodeId).HasColumnName("TruckExcessPalletSlowRateCodeID");
            entity.Property(e => e.TruckExcessPalletSuperRateCodeId).HasColumnName("TruckExcessPalletSuperRateCodeID");
            entity.Property(e => e.TruckExcessWeightFastRateCodeId).HasColumnName("TruckExcessWeightFastRateCodeID");
            entity.Property(e => e.TruckExcessWeightSlowRateCodeId).HasColumnName("TruckExcessWeightSlowRateCodeID");
            entity.Property(e => e.TruckExcessZoneRateCodeId).HasColumnName("TruckExcessZoneRateCodeID");
            entity.Property(e => e.TruckExpressExcessZoneRateCodeId).HasColumnName("TruckExpressExcessZoneRateCodeID");
            entity.Property(e => e.TruckRateCodeId).HasColumnName("TruckRateCodeID");
            entity.Property(e => e.TruckRoadRateCodeId).HasColumnName("TruckRoadRateCodeID");
            entity.Property(e => e.TruckStandardExcessZoneRateCodeId).HasColumnName("TruckStandardExcessZoneRateCodeID");
            entity.Property(e => e.TruckSuperExcessZoneRateCodeId).HasColumnName("TruckSuperExcessZoneRateCodeID");
            entity.Property(e => e.UcclAccountStatus).HasColumnName("ucclAccountStatus");
            entity.Property(e => e.UcclActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_ucclActive")
                .HasColumnName("ucclActive");
            entity.Property(e => e.UcclAddress)
                .HasMaxLength(150)
                .HasColumnName("ucclAddress");
            entity.Property(e => e.UcclAverageDaily)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_ucclAverageDaily")
                .HasColumnType("money")
                .HasColumnName("ucclAverageDaily");
            entity.Property(e => e.UcclAverageDailyGroup)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_ucclAverageDailyGroup")
                .HasColumnName("ucclAverageDailyGroup");
            entity.Property(e => e.UcclAwesome).HasColumnName("ucclAwesome");
            entity.Property(e => e.UcclBillingType).HasColumnName("ucclBillingType");
            entity.Property(e => e.UcclCash).HasColumnName("ucclCash");
            entity.Property(e => e.UcclCode)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("ucclCode");
            entity.Property(e => e.UcclDateJoined)
                .HasColumnType("datetime")
                .HasColumnName("ucclDateJoined");
            entity.Property(e => e.UcclDmfirstName)
                .HasMaxLength(50)
                .HasColumnName("ucclDMFirstName");
            entity.Property(e => e.UcclDmlastName)
                .HasMaxLength(50)
                .HasColumnName("ucclDMLastName");
            entity.Property(e => e.UcclExtraAddress)
                .HasMaxLength(550)
                .HasColumnName("ucclExtraAddress");
            entity.Property(e => e.UcclFax)
                .HasMaxLength(50)
                .HasColumnName("ucclFax");
            entity.Property(e => e.UcclGroupId)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_ucclGroupID")
                .HasColumnName("ucclGroupID");
            entity.Property(e => e.UcclGstinc).HasColumnName("ucclGSTInc");
            entity.Property(e => e.UcclInActiveDate)
                .HasColumnType("datetime")
                .HasColumnName("ucclInActiveDate");
            entity.Property(e => e.UcclInActiveSetBy)
                .HasMaxLength(50)
                .HasColumnName("ucclInActiveSetBy");
            entity.Property(e => e.UcclIndustry).HasColumnName("ucclIndustry");
            entity.Property(e => e.UcclInternal).HasColumnName("ucclInternal");
            entity.Property(e => e.UcclInternet)
                .HasMaxLength(100)
                .HasColumnName("ucclInternet");
            entity.Property(e => e.UcclLegalName)
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnName("ucclLegalName");
            entity.Property(e => e.UcclMcfirstName)
                .HasMaxLength(50)
                .HasColumnName("ucclMCFirstName");
            entity.Property(e => e.UcclMclastName)
                .HasMaxLength(50)
                .HasColumnName("ucclMCLastName");
            entity.Property(e => e.UcclMobile)
                .HasMaxLength(50)
                .HasColumnName("ucclMobile");
            entity.Property(e => e.UcclName)
                .IsRequired()
                .HasMaxLength(75)
                .HasColumnName("ucclName");
            entity.Property(e => e.UcclNote)
                .HasColumnType("ntext")
                .HasColumnName("ucclNote");
            entity.Property(e => e.UcclNotes)
                .HasMaxLength(550)
                .HasColumnName("ucclNotes");
            entity.Property(e => e.UcclPassword)
                .HasMaxLength(50)
                .HasColumnName("ucclPassword");
            entity.Property(e => e.UcclPedal).HasColumnName("ucclPedal");
            entity.Property(e => e.UcclPhone)
                .HasMaxLength(50)
                .HasColumnName("ucclPhone");
            entity.Property(e => e.UcclPhone2)
                .HasMaxLength(50)
                .HasColumnName("ucclPhone2");
            entity.Property(e => e.UcclPodrequired).HasColumnName("ucclPODRequired");
            entity.Property(e => e.UcclPostCode)
                .HasMaxLength(50)
                .HasColumnName("ucclPostCode");
            entity.Property(e => e.UcclPostal)
                .HasMaxLength(150)
                .HasColumnName("ucclPostal");
            entity.Property(e => e.UcclRate).HasColumnName("ucclRate");
            entity.Property(e => e.UcclRateDoc)
                .HasDefaultValue(69)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_ucclRateDoc")
                .HasColumnName("ucclRateDoc");
            entity.Property(e => e.UcclRateMainTrunk)
                .HasDefaultValue(70)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_ucclRateMainTrunk")
                .HasColumnName("ucclRateMainTrunk");
            entity.Property(e => e.UcclRateMainTrunkKg)
                .HasDefaultValue(71)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_ucclRateMainTrunkKG")
                .HasColumnName("ucclRateMainTrunkKG");
            entity.Property(e => e.UcclRateNi)
                .HasDefaultValue(67)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_ucclRateNI")
                .HasColumnName("ucclRateNI");
            entity.Property(e => e.UcclRateNiweight)
                .HasDefaultValue(74)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_ucclRateNIWeight")
                .HasColumnName("ucclRateNIWeight");
            entity.Property(e => e.UcclRateOther)
                .HasDefaultValue(72)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_ucclRateOther")
                .HasColumnName("ucclRateOther");
            entity.Property(e => e.UcclRateOtherKg)
                .HasDefaultValue(73)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_ucclRateOtherKG")
                .HasColumnName("ucclRateOtherKG");
            entity.Property(e => e.UcclRateShorthaul)
                .HasDefaultValue(76)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_ucclRateShorhaul")
                .HasColumnName("ucclRateShorthaul");
            entity.Property(e => e.UcclRateShorthaulKg)
                .HasDefaultValue(77)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_ucclRateShorthaulKG")
                .HasColumnName("ucclRateShorthaulKG");
            entity.Property(e => e.UcclRateSi)
                .HasDefaultValue(68)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_ucclRateSI")
                .HasColumnName("ucclRateSI");
            entity.Property(e => e.UcclRateSiweight)
                .HasDefaultValue(75)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_ucclRateSIWeight")
                .HasColumnName("ucclRateSIWeight");
            entity.Property(e => e.UcclReferralNotes)
                .HasColumnType("ntext")
                .HasColumnName("ucclReferralNotes");
            entity.Property(e => e.UcclReferralSource).HasColumnName("ucclReferralSource");
            entity.Property(e => e.UcclSlow).HasColumnName("ucclSlow");
            entity.Property(e => e.UcclStaff).HasColumnName("ucclStaff");
            entity.Property(e => e.UcclSuburbId).HasColumnName("ucclSuburbID");
            entity.Property(e => e.UcclType)
                .HasMaxLength(50)
                .HasColumnName("ucclType");
            entity.Property(e => e.UcclUseGroup)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_ucclUseGroup")
                .HasColumnName("ucclUseGroup");
            entity.Property(e => e.Ucclemail)
                .HasMaxLength(100)
                .HasColumnName("ucclemail");
            entity.Property(e => e.UrgentTonightActive).HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_UrgentTonightActive");
            entity.Property(e => e.UrgentTonightCategoryId).HasColumnName("UrgentTonightCategoryID");
            entity.Property(e => e.UrgentTonightLogo).HasMaxLength(500);
            entity.Property(e => e.UrgentTonightSequence).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UrgentTonightShow).HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_UrgentTonightShow");
            entity.Property(e => e.UrgentTonightStyleSheet).HasMaxLength(500);
            entity.Property(e => e.UtaddtionalItemRateCodeId).HasColumnName("UTAddtionalItemRateCodeID");
            entity.Property(e => e.UtcutOff)
                .HasColumnType("datetime")
                .HasColumnName("UTCutOff");
            entity.Property(e => e.UtminimumJobsAmount)
                .HasColumnType("money")
                .HasColumnName("UTMinimumJobsAmount");
            entity.Property(e => e.UtminimumJobsPerDay).HasColumnName("UTMinimumJobsPerDay");
            entity.Property(e => e.UtpickupTime)
                .HasColumnType("datetime")
                .HasColumnName("UTPickupTime");
            entity.Property(e => e.UtrateCodeId).HasColumnName("UTRateCodeID");
            entity.Property(e => e.WebServicePassword).HasMaxLength(100);
            entity.Property(e => e.WhenBookingJobDisplayFullName).HasAnnotation("Relational:DefaultConstraintName", "DF_tucClient_WhenBookingJobDisplayFullName");
            entity.Property(e => e.XeroId).HasMaxLength(50);
        });

        modelBuilder.Entity<TucEventTemplate>(entity =>
        {
            entity.HasKey(e => e.UcetId).HasName("PK__tucEvent__F4DE3077897F21BD");

            entity.ToTable("tucEventTemplate");

            entity.HasIndex(e => e.UcetClientId, "IX_tucEventTemplate_Client");

            entity.HasIndex(e => e.UcetName, "IX_tucEventTemplate_Name");

            entity.HasIndex(e => e.UcetSpeedId, "IX_tucEventTemplate_Speed");

            entity.Property(e => e.UcetId).HasColumnName("ucetID");
            entity.Property(e => e.UcetClientId).HasColumnName("ucetClientID");
            entity.Property(e => e.UcetCreated)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("ucetCreated");
            entity.Property(e => e.UcetCreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("ucetCreatedBy");
            entity.Property(e => e.UcetDescription)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("ucetDescription");
            entity.Property(e => e.UcetIsActive)
                .HasDefaultValue(true)
                .HasColumnName("ucetIsActive");
            entity.Property(e => e.UcetLastModified)
                .HasColumnType("datetime")
                .HasColumnName("ucetLastModified");
            entity.Property(e => e.UcetLastModifiedBy)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("ucetLastModifiedBy");
            entity.Property(e => e.UcetName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("ucetName");
            entity.Property(e => e.UcetSpeedId).HasColumnName("ucetSpeedID");

            entity.HasOne(d => d.UcetClient).WithMany(p => p.TucEventTemplates)
                .HasForeignKey(d => d.UcetClientId)
                .HasConstraintName("FK_tucEventTemplate_Client");

            entity.HasOne(d => d.UcetSpeed).WithMany(p => p.TucEventTemplates)
                .HasForeignKey(d => d.UcetSpeedId)
                .HasConstraintName("FK_tucEventTemplate_Speed");
        });

        modelBuilder.Entity<TucEventTemplateDetail>(entity =>
        {
            entity.HasKey(e => e.UcetdId).HasName("PK__tucEvent__561E9FFEE41BC02D");

            entity.ToTable("tucEventTemplateDetail");

            entity.HasIndex(e => e.UcetdStatusId, "IX_tucEventTemplateDetail_Status");

            entity.HasIndex(e => e.UcetdTemplateId, "IX_tucEventTemplateDetail_Template");

            entity.Property(e => e.UcetdId).HasColumnName("ucetdID");
            entity.Property(e => e.UcetdEventTypeId).HasColumnName("ucetdEventTypeID");
            entity.Property(e => e.UcetdIsActive)
                .HasDefaultValue(true)
                .HasColumnName("ucetdIsActive");
            entity.Property(e => e.UcetdSequence).HasColumnName("ucetdSequence");
            entity.Property(e => e.UcetdStatusId).HasColumnName("ucetdStatusID");
            entity.Property(e => e.UcetdTemplateId).HasColumnName("ucetdTemplateID");
            entity.Property(e => e.UcetdTimeOffset).HasColumnName("ucetdTimeOffset");

            entity.HasOne(d => d.UcetdEventType).WithMany(p => p.TucEventTemplateDetails)
                .HasForeignKey(d => d.UcetdEventTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tucEventTemplateDetail_EventType");

            entity.HasOne(d => d.UcetdStatus).WithMany(p => p.TucEventTemplateDetails)
                .HasForeignKey(d => d.UcetdStatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tucEventTemplateDetail_Status");

            entity.HasOne(d => d.UcetdTemplate).WithMany(p => p.TucEventTemplateDetails)
                .HasForeignKey(d => d.UcetdTemplateId)
                .HasConstraintName("FK_tucEventTemplateDetail_Template");
        });

        modelBuilder.Entity<TucEventType>(entity =>
        {
            entity.HasKey(e => e.UcetId)
                .IsClustered(false)
                .HasAnnotation("SqlServer:FillFactor", 80);

            entity.ToTable("tucEventType");

            entity.Property(e => e.UcetId).HasColumnName("ucetID");
            entity.Property(e => e.UcetGroup)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("ucetGroup");
            entity.Property(e => e.UcetName)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("ucetName");
        });

        modelBuilder.Entity<TucEventTypeEventTypeGroup>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TucEvent__3214EC0756C5C0B3");

            entity.ToTable("TucEventType_EventTypeGroups");

            entity.HasIndex(e => e.EventTypeGroupId, "IX_TucEventType_EventTypeGroups_EventTypeGroupId");

            entity.HasIndex(e => e.EventTypeId, "IX_TucEventType_EventTypeGroups_EventTypeId");

            entity.HasIndex(e => new { e.EventTypeId, e.EventTypeGroupId }, "UQ_TucEventType_EventTypeGroups").IsUnique();

            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Sequence).HasDefaultValue(1);

            entity.HasOne(d => d.EventTypeGroup).WithMany(p => p.TucEventTypeEventTypeGroups)
                .HasForeignKey(d => d.EventTypeGroupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TucEventType_EventTypeGroups_TucEventTypeGroups");

            entity.HasOne(d => d.EventType).WithMany(p => p.TucEventTypeEventTypeGroups)
                .HasForeignKey(d => d.EventTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TucEventType_EventTypeGroups_TucEventType");
        });

        modelBuilder.Entity<TucEventTypeGroup>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TucEvent__3214EC076F5DF1F4");

            entity.Property(e => e.Created)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.LastModified).HasColumnType("datetime");
            entity.Property(e => e.LastModifiedBy).HasMaxLength(50);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<TucJobStatus>(entity =>
        {
            entity.HasKey(e => e.UcjsId)
                .IsClustered(false)
                .HasAnnotation("SqlServer:FillFactor", 80);

            entity.ToTable("tucJobStatus");

            entity.HasIndex(e => e.JobStatusNotificationId, "IX_tucJobStatus_JobStatusNotificationID");

            entity.Property(e => e.UcjsId).HasColumnName("ucjsID");
            entity.Property(e => e.JobStatusNotificationId).HasColumnName("JobStatusNotificationID");
            entity.Property(e => e.UcjsCode)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("ucjsCode");
            entity.Property(e => e.UcjsName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("ucjsName");
            entity.Property(e => e.UcjsReplyCode)
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("ucjsReplyCode");
        });

        modelBuilder.Entity<TucJobType>(entity =>
        {
            entity.HasKey(e => e.UcjtId)
                .IsClustered(false)
                .HasAnnotation("SqlServer:FillFactor", 80);

            entity.ToTable("tucJobType");

            entity.HasIndex(e => e.DeliveryTime, "DeliveryTime");

            entity.HasIndex(e => e.ServiceTrackingId, "FK_ServiceTrackingId");

            entity.HasIndex(e => e.Minutes, "Minuties");

            entity.HasIndex(e => e.PickupTime, "PickUpTime");

            entity.Property(e => e.UcjtId).HasColumnName("ucjtID");
            entity.Property(e => e.AddonPercentage).HasColumnType("decimal(5, 4)");
            entity.Property(e => e.Alias).HasMaxLength(500);
            entity.Property(e => e.CourierPercentage).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.Created).HasColumnType("datetime");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.DatacomEntry).HasAnnotation("Relational:DefaultConstraintName", "DF_tucJobType_DatacomEntry");
            entity.Property(e => e.ExtraName).HasMaxLength(50);
            entity.Property(e => e.Faf).HasColumnName("FAF");
            entity.Property(e => e.JobEntry).HasAnnotation("Relational:DefaultConstraintName", "DF_tucJobType_JobEntry");
            entity.Property(e => e.JobLetter).HasMaxLength(5);
            entity.Property(e => e.LastModified).HasColumnType("datetime");
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Mfv).HasColumnName("MFV");
            entity.Property(e => e.NationwideEntry).HasAnnotation("Relational:DefaultConstraintName", "DF_tucJobType_NationwideEntry");
            entity.Property(e => e.Notes).HasColumnType("ntext");
            entity.Property(e => e.ShortName).HasMaxLength(50);
            entity.Property(e => e.ShowPhotosWhenChild).HasDefaultValue(true);
            entity.Property(e => e.SuccessRate).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.SystemName).HasMaxLength(50);
            entity.Property(e => e.UcjtBaseRate)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucJobType_ucjtBaseRate")
                .HasColumnType("money")
                .HasColumnName("ucjtBaseRate");
            entity.Property(e => e.UcjtClientId).HasColumnName("ucjtClientID");
            entity.Property(e => e.UcjtCode)
                .HasMaxLength(10)
                .IsFixedLength()
                .HasColumnName("ucjtCode");
            entity.Property(e => e.UcjtDescription)
                .HasMaxLength(500)
                .HasColumnName("ucjtDescription");
            entity.Property(e => e.UcjtName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("ucjtName");
            entity.Property(e => e.UcjtUnitRate)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tucJobType_ucjtUnitRate")
                .HasColumnType("money")
                .HasColumnName("ucjtUnitRate");
            entity.Property(e => e.WebJobEntry).HasAnnotation("Relational:DefaultConstraintName", "DF_tucJobType_WebJobEntry");
            entity.Property(e => e.WebServiceEntry).HasAnnotation("Relational:DefaultConstraintName", "DF_tucJobType_WebServiceEntry");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}