// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class DispatchRouteRoster
{
    public int RouteRosterId { get; set; }

    public int RouteId { get; set; }

    public int? CourierId { get; set; }

    public DateTime? RosterDate { get; set; }

    public byte? DayOfWeek { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public byte? TargetType { get; set; }

    public int? AgentId { get; set; }

    public virtual TucAgent Agent { get; set; }

    public virtual TucCourier Courier { get; set; }

    public virtual Route Route { get; set; }
}