// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class DispatchLinehaulRunRoster
{
    public int LinehaulRunRosterId { get; set; }

    public int LinehaulRunId { get; set; }

    public int? CourierId { get; set; }

    public int? VehicleId { get; set; }

    public DateTime? RosterDate { get; set; }

    public byte? DayOfWeek { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public virtual TucCourier Courier { get; set; }

    public virtual TblbulkLinehaulRun LinehaulRun { get; set; }
}