// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

// Driver-by-day roster for linehaul runs (Recurring Routes spec §4). Sibling of
// DispatchRouteRoster but courier-only (no Agent/NP target). IsActive = 0 is the
// soft-delete; one active row per (run, DayOfWeek) via a filtered unique index.
// v1 uses the weekly DayOfWeek path (1=Mon..7=Sun); RosterDate + VehicleId are
// schema-ready for v1.1 / v1.5. Backed by migration 20260617090000.
public partial class DispatchLinehaulRunRoster
{
    public int LinehaulRunRosterId { get; set; }

    public int LinehaulRunId { get; set; }

    public int? CourierId { get; set; }

    public int? VehicleId { get; set; }

    public DateTime? RosterDate { get; set; }

    public byte? DayOfWeek { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }
}
