// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class DocumentType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Instructions { get; set; }

    public string Category { get; set; }

    public bool Mandatory { get; set; }

    public bool IsActive { get; set; }

    public bool HasExpiry { get; set; }

    public int ExpiryWarningDays { get; set; }

    public bool BlockOnExpiry { get; set; }

    public string AppliesTo { get; set; }

    public int SortOrder { get; set; }

    public string Purpose { get; set; }

    public string ContentUrl { get; set; }

    public int? EstimatedMinutes { get; set; }

    public bool QuizRequired { get; set; }

    public bool HasTemplate { get; set; }

    public string TemplateFileName { get; set; }

    public string TemplateMimeType { get; set; }

    public string TemplateS3key { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ReviewCriteria { get; set; }

    public int ExpiryUrgentDays { get; set; }

    public virtual ICollection<ComplianceProfileRequirement> ComplianceProfileRequirements { get; set; } = new List<ComplianceProfileRequirement>();

    public virtual ICollection<CourierDocument> CourierDocuments { get; set; } = new List<CourierDocument>();
}