// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class Feature
{
    public string FeatureKey { get; set; }

    public string DisplayName { get; set; }

    public string Description { get; set; }

    public string Category { get; set; }

    // Feature Matrix cascade (FEATURE_MATRIX_CASCADE_2026-06-07) — mirrors the
    // dbo.Permission tree. ParentKey is a plain self-FK column to FeatureKey
    // (NULL = root tier); Tier/SortOrder are advisory (the UI infers depth from
    // the parent walk and falls back to displayName sort). Added by migration
    // 20260608100000_FeatureCascadeColumns.sql.
    public string ParentKey { get; set; }

    public int? Tier { get; set; }

    public int? SortOrder { get; set; }

    // Country/region scope (SEED-SCOPE-ALL-HUBS §2). NULL = available
    // everywhere; otherwise a comma list of ISO country codes the feature is
    // limited to (e.g. 'NZ', 'NZ,AU'). The resolver intersects this with the
    // tenant's CountryCode claim. Added by migration 20260608130000.
    public string AvailableCountries { get; set; }

    public virtual ICollection<ClientTypeFeature> ClientTypeFeatures { get; set; } = new List<ClientTypeFeature>();
}