// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class JobApplication
{
    public int Id { get; set; }

    public int PostingId { get; set; }

    public int ApplicantId { get; set; }

    public string Status { get; set; }

    public DateTime AppliedAt { get; set; }

    public virtual JobPosting Posting { get; set; }
}