// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class JobBarcode
{
    public int Id { get; set; }

    public int JobId { get; set; }

    public string BarcodeValue { get; set; }

    public string BarcodeType { get; set; }

    public DateTime ScannedAt { get; set; }

    public int? ScannedBy { get; set; }

    public decimal? GpsLatitude { get; set; }

    public decimal? GpsLongitude { get; set; }
}