// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class JobPhoto
{
    public int Id { get; set; }

    public int JobId { get; set; }

    public string PhotoType { get; set; }

    public string BlobUrl { get; set; }

    public string ThumbnailUrl { get; set; }

    public DateTime CapturedAt { get; set; }

    public int? CapturedBy { get; set; }

    public decimal? GpsLatitude { get; set; }

    public decimal? GpsLongitude { get; set; }

    public string Notes { get; set; }
}