// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class JobWorkflowStep
{
    public int Id { get; set; }

    public int JobId { get; set; }

    public int TemplateDetailId { get; set; }

    public DateTime? CompletedAt { get; set; }

    public int? CompletedBy { get; set; }

    public string DataType { get; set; }

    public string TextData { get; set; }

    public string BlobUrl { get; set; }

    public decimal? GpsLatitude { get; set; }

    public decimal? GpsLongitude { get; set; }

    public virtual TucEventTemplateDetail TemplateDetail { get; set; }
}