// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class NpFeatureConfig
{
    public int Id { get; set; }

    public int AgentId { get; set; }

    public int? MaxCouriers { get; set; }

    public int? MaxUsersPerRole { get; set; }

    public string CoverageAreasJson { get; set; }

    public string NotificationEmail { get; set; }

    public bool NotifyOnNewJob { get; set; }

    public bool NotifyOnJobUpdate { get; set; }

    public string NotifyDigestFreq { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime UpdatedDate { get; set; }
}