// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class Permission
{
    public string PermissionKey { get; set; }

    public string DisplayName { get; set; }

    public string Description { get; set; }

    public string Category { get; set; }

    public string ParentKey { get; set; }

    public byte Tier { get; set; }

    public byte AccessType { get; set; }

    public int SortOrder { get; set; }

    public virtual ICollection<Permission> InverseParentKeyNavigation { get; set; } = new List<Permission>();

    public virtual Permission ParentKeyNavigation { get; set; }

    public virtual ICollection<RolePermission> RolePermissions { get; set; } = new List<RolePermission>();
}