// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class ProspectAgent
{
    public int Id { get; set; }

    public string CompanyName { get; set; }

    public string ContactName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Website { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string PostCode { get; set; }

    public string Country { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public string ServiceTypes { get; set; }

    public string Certifications { get; set; }

    public int? FleetSize { get; set; }

    public string VehicleTypes { get; set; }

    public int? CoverageRadius { get; set; }

    public string AssociationSource { get; set; }

    public string AssociationMemberId { get; set; }

    public bool IsVerified { get; set; }

    public bool IsActive { get; set; }

    public int? ConvertedToAgentId { get; set; }

    public DateTime? ConvertedDate { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime UpdatedDate { get; set; }

    public virtual ICollection<AgentOnboarding> AgentOnboardings { get; set; } = new List<AgentOnboarding>();

    public virtual ICollection<QuotesQuote> QuotesQuotes { get; set; } = new List<QuotesQuote>();
}