// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class QuotesQuote
{
    public int Id { get; set; }

    public int PostingId { get; set; }

    public int? ProspectAgentId { get; set; }

    public int? AgentId { get; set; }

    public decimal? ProposedRate { get; set; }

    public string RateType { get; set; }

    public string Message { get; set; }

    public int? AvailableFleetSize { get; set; }

    public DateOnly? AvailableStartDate { get; set; }

    public string Status { get; set; }

    public int? ReviewedByUserId { get; set; }

    public DateTime? ReviewedDate { get; set; }

    public string ReviewNotes { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime UpdatedDate { get; set; }

    public DateTime? SubmittedDate { get; set; }

    public DateTime? ExpiredDate { get; set; }

    public virtual ICollection<AgentOnboarding> AgentOnboardings { get; set; } = new List<AgentOnboarding>();

    public virtual QuotesPosting Posting { get; set; }

    public virtual ProspectAgent ProspectAgent { get; set; }
}