// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class QuotesPosting
{
    public int Id { get; set; }

    public int PostedByUserId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string ServiceType { get; set; }

    public string Region { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string PostCode { get; set; }

    public int? CoverageRadiusMiles { get; set; }

    public string EstimatedVolume { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public bool IsOngoing { get; set; }

    public string RequiredCertifications { get; set; }

    public string RequiredVehicleTypes { get; set; }

    public int? MinFleetSize { get; set; }

    public string Status { get; set; }

    public DateTime? PublishedDate { get; set; }

    public DateTime? ClosedDate { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime UpdatedDate { get; set; }

    public virtual ICollection<QuotesQuote> QuotesQuotes { get; set; } = new List<QuotesQuote>();
}