// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class RecruitmentStage
{
    public int Id { get; set; }

    public string StageName { get; set; }

    public int SortOrder { get; set; }

    public bool Enabled { get; set; }

    public bool Mandatory { get; set; }

    public string Description { get; set; }

    public DateTime CreatedDate { get; set; }
}