// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class RolePermission
{
    public int RolePermissionId { get; set; }

    public int ContactRoleId { get; set; }

    public string PermissionKey { get; set; }

    public bool Allowed { get; set; }

    // Unified Permissions §4.3 — graded access (unified ladder):
    // 0=None, 1=View, 2=Edit, 3=Action. NULL = fall back to Allowed
    // (backwards compat during transition). Resolver prefers AccessLevel.
    public byte? AccessLevel { get; set; }

    public int? ClientId { get; set; }

    public virtual TucClient Client { get; set; }

    public virtual TblContactRole ContactRole { get; set; }

    public virtual Permission PermissionKeyNavigation { get; set; }
}