// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class TblbulkLinehaulRun
{
    public int Id { get; set; }

    public string RunName { get; set; }

    public int FromDepotId { get; set; }

    public int ToDepotId { get; set; }

    public TimeOnly? StartTime { get; set; }

    // Nullable since Fixes §5 — a run can be assigned to an Agent/NP instead of
    // a courier (CourierId NULL then; the old 0 "unbound" sentinel is retired —
    // it violated the FK to tucCourier).
    public int? CourierId { get; set; }

    public TimeOnly? DespatchTime { get; set; }

    // Recurring Routes Fixes §5 — polymorphic default target. TargetType:
    // 1=Courier (CourierId), 2=Agent, 3=NetworkPartner (both via DefaultAgentId;
    // NP = agent with IsNetworkPartner=1). Mirrors Route.DefaultTargetType.
    public byte? DefaultTargetType { get; set; }

    public int? DefaultAgentId { get; set; }

    public virtual TucCourier Courier { get; set; }

    public virtual TucAgent DefaultAgent { get; set; }

    public virtual ICollection<DispatchLinehaulRunRoster> DispatchLinehaulRunRosters { get; set; } = new List<DispatchLinehaulRunRoster>();

    public virtual TblBulkRegion FromDepot { get; set; }

    public virtual ICollection<TblBulkScheduleLinehaul> TblBulkScheduleLinehauls { get; set; } = new List<TblBulkScheduleLinehaul>();

    public virtual TblBulkRegion ToDepot { get; set; }
}