// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class TblbulkLinehaulRun
{
    public int Id { get; set; }

    public string RunName { get; set; }

    public int FromDepotId { get; set; }

    public int ToDepotId { get; set; }

    public TimeOnly? StartTime { get; set; }

    public int CourierId { get; set; }

    public TimeOnly? DespatchTime { get; set; }

    public virtual TucCourier Courier { get; set; }

    public virtual ICollection<DispatchLinehaulRunRoster> DispatchLinehaulRunRosters { get; set; } = new List<DispatchLinehaulRunRoster>();

    public virtual TblBulkRegion FromDepot { get; set; }

    public virtual ICollection<TblBulkScheduleLinehaul> TblBulkScheduleLinehauls { get; set; } = new List<TblBulkScheduleLinehaul>();

    public virtual TblBulkRegion ToDepot { get; set; }
}