// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

// Depot-to-depot middle-mile run. Source of truth is the ClientManager domain;
// the configurator owns the tenant-facing Linehaul tab over it (Recurring
// Routes spec §3, native EF — CM's CRUD was thin EF with no side-effects).
// Hand-authored lean to match EF Power Tools output; regen (efpt.config.json
// now ticks tblbulkLinehaulRun) reproduces + expands with depot/schedule navs.
public partial class TblbulkLinehaulRun
{
    public int Id { get; set; }

    public string RunName { get; set; }

    public int FromDepotId { get; set; }

    public int ToDepotId { get; set; }

    public TimeOnly? StartTime { get; set; }

    public int CourierId { get; set; }

    public TimeOnly? DespatchTime { get; set; }
}
