// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class TblBulkScheduleLinehaul
{
    public int Id { get; set; }

    public string Name { get; set; }

    public bool? Active { get; set; }

    public decimal? Amount { get; set; }

    public decimal? AmountPercentage { get; set; }

    public int FromDepotId { get; set; }

    public int ToDepotId { get; set; }

    public bool? InsertToBulk { get; set; }

    public int? Minutes { get; set; }

    public int? BulkRunScheduleId { get; set; }

    public int? LinehaulRunId { get; set; }

    public bool? ApplyDiscount { get; set; }

    public bool? ApplyAddOnPercentage { get; set; }

    public string WeekDay { get; set; }

    public int? DepartureAdvanceDays { get; set; }

    public bool? FromClientAddress { get; set; }

    public int? DropOffLocationId { get; set; }

    public virtual TblBulkRunSchedule BulkRunSchedule { get; set; }

    public virtual TblbulkLinehaulRun LinehaulRun { get; set; }
}