// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

// Schedule→linehaul-run binding (authored by the Schedule editor; read-only
// here). The configurator only reads the active-binding count per run for the
// "Used by Schedules" column + delete guard (Recurring Routes spec §3). Lean
// hand-authored subset; regen expands to the full pricing/timing columns.
public partial class TblBulkScheduleLinehaul
{
    public int Id { get; set; }

    public int? LinehaulRunId { get; set; }

    public bool? Active { get; set; }
}
