// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

// Bulk region = depot. Used for the linehaul From/To depot dropdowns + name
// resolution on the Linehaul tab (Recurring Routes spec §3). Lean subset
// (id/name/active); regen expands to the full address/geo columns.
public partial class TblBulkRegion
{
    public int BulkRegionId { get; set; }

    public string Name { get; set; }

    public bool Active { get; set; }
}
