// <auto-generated> Hand-authored for Unified Permissions §8.1 Tab 3; reconcile on next EF Power Tools regen. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

// Append-only contact-change audit (dbmigrationsv2 20260605100500). Backs the
// Contact modal History tab. ChangedByIsDfAdmin is captured at write time for
// the addendum actor-masking on read.
public partial class TblContactAudit
{
    public int AuditId { get; set; }

    public int ClientContactId { get; set; }

    public string FieldName { get; set; }

    public string OldValue { get; set; }

    public string NewValue { get; set; }

    public string ChangedBy { get; set; }

    public bool ChangedByIsDfAdmin { get; set; }

    public DateTime ChangedAt { get; set; }
}
