// <auto-generated> Hand-authored for Unified Permissions §4.1a; reconcile on next EF Power Tools regen. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

// Junction: contact <-> role for role stacking (spec §4.1a). A contact may
// hold multiple roles; the resolver takes the most-permissive union.
// ClientContactId references tucClientContact PK (ucctID).
public partial class TblContactContactRole
{
    public int ClientContactId { get; set; }

    public int ContactRoleId { get; set; }

    public virtual TblContactRole ContactRole { get; set; }

    public virtual TucClientContact ClientContact { get; set; }
}
