// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class TblContactAudit
{
    public int AuditId { get; set; }

    public int ClientContactId { get; set; }

    public string FieldName { get; set; }

    public string OldValue { get; set; }

    public string NewValue { get; set; }

    public string ChangedBy { get; set; }

    public bool ChangedByIsDfAdmin { get; set; }

    public DateTime ChangedAt { get; set; }

    public virtual TucClientContact ClientContact { get; set; }
}