// <auto-generated> Hand-authored for Unified Permissions §4.4; reconcile on next EF Power Tools regen. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

// CRM relationship-label lookup (spec §4.4). No permission logic.
public partial class TblRelationshipType
{
    public int RelationshipTypeId { get; set; }

    public string Name { get; set; }
}
