// <auto-generated> Hand-authored for Unified Permissions §4.1; reconcile on next EF Power Tools regen. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

// Junction: which ClientTypes a role may be assigned to (spec §4.1).
public partial class TblRoleClientType
{
    public int ContactRoleId { get; set; }

    public int ClientTypeId { get; set; }

    public virtual TblContactRole ContactRole { get; set; }

    public virtual ClientType ClientType { get; set; }
}
