// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class TblRelationshipType
{
    public int RelationshipTypeId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<TucClientContact> TucClientContacts { get; set; } = new List<TucClientContact>();
}