// <auto-generated> Hand-authored for Agent/NP Document Compliance (2026-06-10); reconcile on next EF Power Tools regen. </auto-generated>
#nullable disable
using System;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

// Post-activation business-document compliance instance against an agent / NP.
// Mirrors CourierDocument (database/040 mirrors 035) but keyed to tucAgent.
// File bytes live in S3; this row holds the key + lifecycle + (Phase 3) the
// AI-suggested decision/expiry. Mapped in DynamicDespatchDbContext (excluded
// from the EFPT scaffold so the configuration survives regen).
public partial class TucAgentDocument
{
    public int UcadId { get; set; }
    public int AgentId { get; set; }                // -> tucAgents.ucagID
    public int DocumentTypeId { get; set; }         // -> DocumentTypes.Id

    public string S3Key { get; set; }
    public string FileName { get; set; }
    public string ContentType { get; set; }
    public long Length { get; set; }

    public DateTime UploadedDate { get; set; }
    public string UploadedBy { get; set; }

    // Verify lifecycle: Pending | Verified | Rejected
    public string VerifyStatus { get; set; }
    public DateTime? VerifiedDate { get; set; }
    public string VerifiedBy { get; set; }
    public string RejectReason { get; set; }

    public DateOnly? ExpiryDate { get; set; }

    // Phase 3 — advisory AI review (nullable until populated).
    public string AiSuggestedDecision { get; set; } // accept | reject | needs_review
    public DateOnly? AiSuggestedExpiry { get; set; }
    public string AiRationale { get; set; }
    public string AiModel { get; set; }
    public DateTime? AiReviewedDate { get; set; }

    public bool IsActive { get; set; }
    public DateTime CreatedDate { get; set; }
    public DateTime? ModifiedDate { get; set; }

    // Join to DocumentTypes for the display name (no inverse collection on
    // DocumentType — deliberate, to avoid widening the EFPT-scaffolded entity).
    public virtual DocumentType DocumentType { get; set; }
}
