// <auto-generated> Hand-authored for Agent/NP Onboarding (2026-06-09); reconcile on next EF Power Tools regen. </auto-generated>
#nullable disable
using System;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

// One row per required onboarding/compliance document.
public partial class TucAgentOnboardingCompliance
{
    public int UcaodId { get; set; }
    public int UcaoId { get; set; }
    public string RequirementKey { get; set; }
    public string Label { get; set; }
    public string Status { get; set; }            // complete / in_progress / missing
    public DateTime? UpdatedAt { get; set; }
    public string Notes { get; set; }

    public virtual TucAgentOnboarding Onboarding { get; set; }
}
