// <auto-generated> Hand-authored for Agent/NP Onboarding (2026-06-09); reconcile on next EF Power Tools regen. </auto-generated>
#nullable disable
using System;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

// Audit-style timeline event shown in the onboarding workspace.
public partial class TucAgentOnboardingTimeline
{
    public int UcaotId { get; set; }
    public int UcaoId { get; set; }
    public string Title { get; set; }
    public string Detail { get; set; }
    public string Owner { get; set; }
    public DateTime EventAt { get; set; }

    public virtual TucAgentOnboarding Onboarding { get; set; }
}
