// <auto-generated> Hand-authored for Agent/NP Onboarding (2026-06-09); reconcile on next EF Power Tools regen. </auto-generated>
#nullable disable
using System;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

// Normalized coverage area for an onboarding record.
public partial class TucAgentOnboardingCoverageArea
{
    public int UcaocId { get; set; }
    public int UcaoId { get; set; }
    public string AreaName { get; set; }

    public virtual TucAgentOnboarding Onboarding { get; set; }
}
