// <auto-generated> Hand-authored for Agent/NP Onboarding (2026-06-09); reconcile on next EF Power Tools regen. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

// Pre-activation onboarding pipeline record. One row per candidate / prospect /
// pending NP. On activation the service promotes it into a real tucAgents row
// and stores the resulting ucagID here. Mapped in DynamicDespatchDbContext
// (excluded from EFPT scaffold so the configuration survives regen).
public partial class TucAgentOnboarding
{
    public int UcaoId { get; set; }
    public int? UcagId { get; set; }
    public string BusinessName { get; set; }
    public string PrimaryContact { get; set; }
    public string Phone { get; set; }
    public string Email { get; set; }
    public string AddressLine1 { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string Association { get; set; }
    public string AssociationMemberId { get; set; }
    public string Source { get; set; }
    public string Stage { get; set; }
    public string NetworkPartnerStatus { get; set; }
    public string FleetProfile { get; set; }
    public int? EstimatedDrivers { get; set; }
    public string ServiceCapabilities { get; set; }   // CSV
    public string Specialties { get; set; }           // CSV
    public string Notes { get; set; }
    public string Reviewer { get; set; }
    public string Owner { get; set; }
    public bool Archived { get; set; }
    public DateTime Created { get; set; }
    public string CreatedBy { get; set; }
    public DateTime LastModified { get; set; }
    public string LastModifiedBy { get; set; }

    public virtual TucAgent Agent { get; set; }
    public virtual ICollection<TucAgentOnboardingCoverageArea> CoverageAreas { get; set; } = new List<TucAgentOnboardingCoverageArea>();
    public virtual ICollection<TucAgentOnboardingCompliance> ComplianceItems { get; set; } = new List<TucAgentOnboardingCompliance>();
    public virtual ICollection<TucAgentOnboardingTimeline> TimelineEvents { get; set; } = new List<TucAgentOnboardingTimeline>();
}
