// <auto-generated> Hand-authored for Agent/NP client compliance overlays (2026-06-11); reconcile on next EF Power Tools regen. </auto-generated>
#nullable disable
using System;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

// Many-to-many: a client ComplianceProfile assigned to an agent/NP (Phase 4b-ii).
// The agent's scorecard unions the base NP doc types with the assigned profiles'
// required doc types. Mapped in DynamicDespatchDbContext (excluded from EFPT
// scaffold so the configuration survives regen).
public partial class TucAgentComplianceProfile
{
    public int UacpId { get; set; }
    public int AgentId { get; set; }        // -> tucAgents.ucagID
    public int ProfileId { get; set; }      // -> ComplianceProfiles.Id
    public DateTime AssignedDate { get; set; }
    public string AssignedBy { get; set; }
}
