// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class TucAgentStatus
{
    public int AgentStatusId { get; set; }

    public string AgentStatusName { get; set; }

    public virtual ICollection<TucAgent> TucAgents { get; set; } = new List<TucAgent>();
}