// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class TucEventTemplate
{
    public int UcetId { get; set; }

    public string UcetName { get; set; }

    public string UcetDescription { get; set; }

    public int? UcetClientId { get; set; }

    public int? UcetSpeedId { get; set; }

    public bool UcetIsActive { get; set; }

    public DateTime UcetCreated { get; set; }

    public string UcetCreatedBy { get; set; }

    public DateTime? UcetLastModified { get; set; }

    public string UcetLastModifiedBy { get; set; }

    public bool UcetMirrorToAgentPortal { get; set; }

    public string UcetCategory { get; set; }

    public bool MirrorToAgentPortal { get; set; }

    public virtual ICollection<TucEventTemplateDetail> TucEventTemplateDetails { get; set; } = new List<TucEventTemplateDetail>();

    public virtual TucClient UcetClient { get; set; }

    public virtual TucJobType UcetSpeed { get; set; }
}