// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class TucEventType
{
    public int UcetId { get; set; }

    public string UcetGroup { get; set; }

    public string UcetName { get; set; }

    public virtual ICollection<AccessorialWorkflowTask> AccessorialWorkflowTasks { get; set; } = new List<AccessorialWorkflowTask>();

    public virtual ICollection<TucEventTemplateDetail> TucEventTemplateDetails { get; set; } = new List<TucEventTemplateDetail>();

    public virtual ICollection<TucEventTypeEventTypeGroup> TucEventTypeEventTypeGroups { get; set; } = new List<TucEventTypeEventTypeGroup>();
}