// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class TucEventTemplateDetail
{
    public int UcetdId { get; set; }

    public int UcetdTemplateId { get; set; }

    public int UcetdStatusId { get; set; }

    public int UcetdEventTypeId { get; set; }

    public int UcetdTimeOffset { get; set; }

    public int UcetdSequence { get; set; }

    public bool UcetdIsActive { get; set; }

    public virtual ICollection<JobWorkflowStep> JobWorkflowSteps { get; set; } = new List<JobWorkflowStep>();

    public virtual TucEventType UcetdEventType { get; set; }

    public virtual TucJobStatus UcetdStatus { get; set; }

    public virtual TucEventTemplate UcetdTemplate { get; set; }
}