// <auto-generated> Hand-authored (lean) for courier modal §13 Communications (2026-06-22); reconcile on next EF Power Tools regen. </auto-generated>
#nullable disable
using System;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

// Legacy dbo.tucEvent — the Despatch "events" log, repurposed by Admin Manager
// for courier communications (ucevCourierID + ucevType -> tucEventType, Group
// 'CE'). LEAN projection: only the columns courier-comms need + every NOT NULL
// column we must populate on insert (ucevPageCourier / ucevClosed /
// ucevIsScheduled / ucevNotificationSent / ucevDueTime). Mapped in
// DynamicDespatchDbContext (excluded from EFPT scaffold). AdminManager already
// has SELECT/INSERT/UPDATE (database/019).
public partial class TucEvent
{
    public int UcevId { get; set; }                 // ucevID (identity, PK)
    public int? UcevType { get; set; }              // ucevType -> tucEventType.UcetId
    public int? UcevCourierId { get; set; }         // ucevCourierID -> tucCourier
    public string UcevNotes { get; set; }           // ucevNotes (varchar 1000)
    public string UcevDescription { get; set; }     // ucevDescription (varchar 255)
    public DateTime? UcevDate { get; set; }         // ucevDate
    public DateTime? UcevTime { get; set; }         // ucevTime
    public int? UcevOriginator { get; set; }        // ucevOriginator (staff id)
    public string UcevDespatcher { get; set; }      // ucevDespatcher (varchar 15)

    // NOT NULL columns — must be set on every insert (no DB default to rely on).
    public bool UcevPageCourier { get; set; }
    public bool UcevClosed { get; set; }
    public bool UcevIsScheduled { get; set; }
    public bool UcevNotificationSent { get; set; }
    public DateTime UcevDueTime { get; set; }
}
