// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class TucJobStatus
{
    public int UcjsId { get; set; }

    public string UcjsReplyCode { get; set; }

    public string UcjsName { get; set; }

    public string UcjsCode { get; set; }

    public int? JobStatusNotificationId { get; set; }

    public virtual ICollection<TucEventTemplateDetail> TucEventTemplateDetails { get; set; } = new List<TucEventTemplateDetail>();
}