// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class TucRegion
{
    public int UcreId { get; set; }

    public string UcreName { get; set; }

    public string UcreDescription { get; set; }
}