// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class ZipPolygonCity
{
    public int ZipPolygonCityId { get; set; }

    public int ZipPolygonId { get; set; }

    public string CityName { get; set; }

    public string State { get; set; }

    public bool Primary { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ZipPolygon ZipPolygon { get; set; }
}