// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfrntDriveConfigurator.Core.Domain.Despatch;

public partial class ZipPolygon
{
    public int ZipPolygonId { get; set; }

    public string Zip { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public long? LandAreaSqM { get; set; }

    public long? WaterAreaSqM { get; set; }

    public string Wkt { get; set; }

    public virtual ICollection<AgentCoverageAreaZipcode> AgentCoverageAreaZipcodes { get; set; } = new List<AgentCoverageAreaZipcode>();

    public virtual ICollection<ZipPolygonCity> ZipPolygonCities { get; set; } = new List<ZipPolygonCity>();

    public virtual ICollection<Route> Routes { get; set; } = new List<Route>();
}